development:
  adapter: postgresql
  encoding: unicode
  database: publicator_dev
  pool: 5
  username: vagrant
  password: vagrant

test:
  adapter: postgresql
  encoding: unicode
  database: publicator_test
  pool: 5
  username: vagrant
  password: vagrant
